module.exports = [
    {
      emoji: "🍎",
      name: "Apple",
      quantity: 10,
      price: 2,
      tags: ["fruit", "healthy", "snack"],
    },
    {
      emoji: "🍕",
      name: "Pizza",
      quantity: 5,
      price: 10,
      tags: ["fast food", "dinner", "cheese"],
    },
    {
      emoji: "📱",
      name: "Phone",
      quantity: 20,
      price: 500,
      tags: ["electronics", "technology", "communication"],
    },
    {
      emoji: "📚",
      name: "Book",
      quantity: 15,
      price: 15,
      tags: ["literature", "education", "reading"],
    },
    {
      emoji: "🥦",
      name: "Broccoli",
      quantity: 8,
      price: 3,
      tags: ["vegetable", "healthy", "dinner"],
    },
    {
      emoji: "🍔",
      name: "Burger",
      quantity: 12,
      price: 8,
      tags: ["fast food", "lunch", "beef"],
    },
    {
      emoji: "💻",
      name: "Laptop",
      quantity: 25,
      price: 1000,
      tags: ["electronics", "technology", "work"],
    },
    {
      emoji: "🎮",
      name: "Game Console",
      quantity: 10,
      price: 300,
      tags: ["electronics", "gaming", "entertainment"],
    },
    {
      emoji: "👟",
      name: "Sneakers",
      quantity: 30,
      price: 50,
      tags: ["clothing", "footwear", "sport"],
    },
    {
      emoji: "🍇",
      name: "Grapes",
      quantity: 20,
      price: 5,
      tags: ["fruit", "snack", "dessert"],
    },
    {
      emoji: "🍦",
      name: "Ice Cream",
      quantity: 10,
      price: 4,
      tags: ["dessert", "snack", "sweet"],
    },
    {
      emoji: "🥪",
      name: "Sandwich",
      quantity: 15,
      price: 6,
      tags: ["lunch", "snack", "quick meal"],
    },
    {
      emoji: "🧁",
      name: "Cupcake",
      quantity: 20,
      price: 3,
      tags: ["dessert", "snack", "sweet"],
    },
    {
      emoji: "📷",
      name: "Camera",
      quantity: 18,
      price: 800,
      tags: ["electronics", "photography", "hobby"],
    },
    {
      emoji: "🍟",
      name: "French Fries",
      quantity: 10,
      price: 3,
      tags: ["snack", "fast food", "side dish"],
    },
    {
      emoji: "🎧",
      name: "Headphones",
      quantity: 25,
      price: 80,
      tags: ["electronics", "music", "audio"],
    },
    {
      emoji: "🥛",
      name: "Milk",
      quantity: 15,
      price: 2,
      tags: ["beverage", "dairy", "breakfast"],
    },
    {
      emoji: "🍓",
      name: "Strawberry",
      quantity: 30,
      price: 4,
      tags: ["fruit", "snack", "dessert"],
    },
    {
      emoji: "🍣",
      name: "Sushi",
      quantity: 10,
      price: 12,
      tags: ["Japanese", "dinner", "seafood"],
    },
    {
      emoji: "👕",
      name: "T-Shirt",
      quantity: 35,
      price: 15,
      tags: ["clothing", "casual", "top"],
    },
    {
      emoji: "🍰",
      name: "Cake",
      quantity: 8,
      price: 20,
      tags: ["dessert", "celebration", "sweet"],
    },
    {
      emoji: "🥤",
      name: "Soda",
      quantity: 20,
      price: 1.5,
      tags: ["beverage", "drink", "refreshment"],
    },
    {
      emoji: "🥑",
      name: "Avocado",
      quantity: 10,
      price: 3,
      tags: ["fruit", "healthy", "ingredient"],
    },
    {
      emoji: "🍩",
      name: "Donut",
      quantity: 12,
      price: 2,
      tags: ["snack", "dessert", "sweet"],
    },
    {
      emoji: "🥨",
      name: "Pretzel",
      quantity: 15,
      price: 1.5,
      tags: ["snack", "baked", "salty"],
    },
    {
      emoji: "📦",
      name: "Package",
      quantity: 100,
      price: 5,
      tags: ["shipping", "delivery", "container"],
    },
    {
      emoji: "🍔",
      name: "Cheeseburger",
      quantity: 8,
      price: 9,
      tags: ["fast food", "lunch", "cheese"],
    },
    {
      emoji: "🥗",
      name: "Salad",
      quantity: 10,
      price: 7,
      tags: ["healthy", "lunch", "vegetable"],
    },
    {
      emoji: "🍉",
      name: "Watermelon",
      quantity: 5,
      price: 6,
      tags: ["fruit", "summer", "refreshing"],
    },
    {
      emoji: "🎒",
      name: "Backpack",
      quantity: 20,
      price: 30,
      tags: ["accessory", "school", "travel"],
    },
    {
      emoji: "🥐",
      name: "Croissant",
      quantity: 12,
      price: 2.5,
      tags: ["snack", "breakfast", "baked"],
    },
  ];
  